apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: aws-load-balancer-controller
        git:
          url: https://github.com/giantswarm/aws-load-balancer-controller-upstream
          ref: "release-2.8"
        includePaths:
          - helm/aws-load-balancer-controller/**/*
  - path: helm/aws-lb-controller
    contents:
      - path: .
        directory:
          path: vendor/aws-load-balancer-controller/helm/aws-load-balancer-controller
