apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "aws-load-balancer-controller.labels" . | nindent 4 }}
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
  policyTypes:
  - Egress