apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "aws-load-balancer-controller.labels" . | indent 4 }}
spec:
  ports:
  - name: metrics-server
    port: {{ (split ":" .Values.metricsBindAddr)._1 | default 8080 }}
    targetPort: metrics-server
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
